package net.mads.createexpansion.recipe.recipes.assembly;

import net.minecraft.core.HolderLookup;
import net.minecraft.data.recipes.RecipeOutput;

public final class AssemblyRecipes {
    private AssemblyRecipes() {
    }

    public static void build(RecipeOutput output, HolderLookup.Provider holderLookup) {
         new AssemblyRecipeBuilder("assembly/casing/andesite_casing")
                 .baseBlock("minecraft:stripped_spruce_wood")
                 .inputItem("create:andesite_alloy", 4)
                 .inputItem("create_expansion:wood_gear", 1)
                 .inputItem("create_expansion:wood_screw", 2)
                 .inputItem("create_expansion:wood_small_gear", 1)
                 .inputItem("create_expansion:wood_screw", 2)
                 .inputItem("create:andesite_alloy", 4)
                 .outputBlock("create:andesite_casing")
                 .save(output);
        new AssemblyRecipeBuilder("assembly/box/andesite_kinetic_input_box")
                .baseBlock("create:andesite_casing")
                .inputItem("create_expansion:wood_gear", 1)
                .inputItem("create_expansion:wood_screw", 2)
                .inputItem("create_expansion:wood_small_gear", 1)
                .inputItem("create_expansion:wood_screw", 2)
                .inputItem("create:shaft", 1)
                .outputBlock("create_expansion:andesite_kinetic_input_box")
                .save(output);
        new AssemblyRecipeBuilder("assembly/box/andesite_kinetic_output_box")
                .baseBlock("create:andesite_casing")
                .inputItem("create_expansion:wood_screw", 1)
                .inputItem("create_expansion:wood_small_gear", 2)
                .inputItem("create_expansion:wood_gear", 1)
                .inputItem("create_expansion:wood_screw", 2)
                .inputItem("create:shaft", 1)
                .outputBlock("create_expansion:andesite_kinetic_output_box")
                .save(output);
        new AssemblyRecipeBuilder("assembly/cogwheel")
                .baseBlock("create:shaft")
                .inputItem("create_expansion:wood_small_gear", 1)
                .inputItem("create_expansion:wood_screw", 2)
                .outputBlock("create:cogwheel")
                .save(output);
        new AssemblyRecipeBuilder("assembly/large_cogwheel")
                .baseBlock("create:shaft")
                .inputItem("create_expansion:wood_gear", 1)
                .inputItem("create_expansion:wood_screw", 2)
                .outputBlock("create:large_cogwheel")
                .save(output);
        new AssemblyRecipeBuilder("assembly/box/andesite_output_bus")
                .baseBlock("create:andesite_casing")
                .inputItem("minecraft:chest", 1)
                .inputItem("create_expansion:wood_small_gear", 1)
                .inputItem("create_expansion:wood_screw", 4)
                .outputBlock("create_expansion:andesite_output_bus")
                .save(output);
        new AssemblyRecipeBuilder("assembly/box/andesite_input_bus")
                .baseBlock("create:andesite_casing")
                .inputItem("minecraft:chest", 1)
                .inputItem("create_expansion:wood_screw", 2)
                .inputItem("create_expansion:wood_small_gear", 1)
                .inputItem("create_expansion:wood_screw", 2)
                .outputBlock("create_expansion:andesite_input_bus")
                .save(output);
        new AssemblyRecipeBuilder("assembly/box/andesite_muffler")
                .baseBlock("create:andesite_casing")
                .inputItem("minecraft:iron_bars", 2)
                .inputItem("create_expansion:wood_screw", 8)
                .inputItem("create_expansion:wood_gear", 1)
                .inputItem("create_expansion:wood_small_gear", 1)
                .outputBlock("create_expansion:andesite_muffler")
                .save(output);
        new AssemblyRecipeBuilder("assembly/box/andesite_output_hatch")
                .baseBlock("create:andesite_casing")
                .inputItem("minecraft:bucket", 1)
                .inputItem("create_expansion:wood_screw", 2)
                .inputItem("create_expansion:wood_gear", 1)
                .outputBlock("create_expansion:andesite_output_hatch")
                .save(output);
        new AssemblyRecipeBuilder("assembly/box/andesite_input_hatch")
                .baseBlock("create:andesite_casing")
                .inputItem("minecraft:bucket", 1)
                .inputItem("create_expansion:wood_gear", 2)
                .inputItem("create_expansion:wood_screw", 1)
                .outputBlock("create_expansion:andesite_input_hatch")
                .save(output);
        new AssemblyRecipeBuilder("assembly/machine/deployer")
                .baseBlock("create:andesite_casing")
                .inputItem("create:electron_tube", 1)
                .inputItem("create_expansion:wood_screw", 2)
                .inputItem("create:shaft", 1)
                .inputItem("create:piston_extension_pole", 1)
                .inputItem("create:brass_hand", 1)
                .inputItem("create_expansion:wood_screw", 2)
                .outputBlock("create:deployer")
                .save(output);
        new AssemblyRecipeBuilder("assembly/machine/mechanical_saw")
                .baseBlock("create:andesite_casing")
                .inputItem("create_expansion:andesite_alloy_tool_head_buzz_saw", 1)
                .inputItem("create_expansion:wood_screw", 2)
                .inputItem("create:shaft", 1)
                .inputItem("create_expansion:wood_screw", 2)
                .outputBlock("create:mechanical_saw")
                .save(output);
        new AssemblyRecipeBuilder("assembly/machine/mechanical_saw_from_wood_gear")
                .baseBlock("create:andesite_casing")
                .inputItem("create_expansion:wood_gear", 64)
                .inputItem("create_expansion:wood_screw", 128)
                .inputItem("create:shaft", 1)
                .inputItem("create_expansion:wood_screw", 2)
                .outputBlock("create:mechanical_saw")
                .save(output);
        new AssemblyRecipeBuilder("assembly/machine/mechanical_drill")
                .baseBlock("create:andesite_casing")
                .inputItem("create_expansion:drill_head", 1)
                .inputItem("create_expansion:wood_screw", 2)
                .inputItem("create:shaft", 1)
                .inputItem("create_expansion:wood_screw", 2)
                .outputBlock("create:mechanical_drill")
                .save(output);
        new AssemblyRecipeBuilder("assembly/machine/mechanical_pump")
                .baseBlock("create:fluid_pipe")
                .inputItem("create:cogwheel", 1)
                .outputBlock("create:mechanical_pump")
                .save(output);
        new AssemblyRecipeBuilder("assembly/machine/smart_fluid_pipe")
                .baseBlock("create:fluid_pipe")
                .inputItem("create:brass_sheet", 1)
                .inputItem("create_expansion:brass_screw", 4)
                .outputBlock("create:electron_tube", 1)
                .outputBlock("create:smart_fluid_pipe")
                .save(output);
        new AssemblyRecipeBuilder("assembly/machine/mechanical_mixer")
                .baseBlock("create:andesite_casing")
                .inputItem("create:piston_extension_pole", 1)
                .inputItem("create:whisk", 1)
                .inputItem("create_expansion:wood_screw", 2)
                .inputItem("create:cogwheel", 1)
                .inputItem("create_expansion:wood_screw", 2)
                .outputBlock("create:mechanical_mixer")
                .save(output);
        new AssemblyRecipeBuilder("assembly/machine/gearbox")
                .baseBlock("create:andesite_casing")
                .inputItem("create:cogwheel", 4)
                .inputItem("create_expansion:wood_screw", 8)
                .outputBlock("create:gearbox")
                .save(output);
        new AssemblyRecipeBuilder("assembly/machine/mechanical_press")
                .baseBlock("create:andesite_casing")
                .inputItem("create:piston_extension_pole", 1)
                .inputItem("create_expansion:wood_screw", 2)
                .inputItem("create:shaft", 1)
                .inputItem("create_expansion:wood_screw", 2)
                .inputItem("create_expansion:wrought_iron_plate", 1)
                .inputItem("create_expansion:wood_screw", 2)
                .outputBlock("create:mechanical_press")
                .save(output);
        new AssemblyRecipeBuilder("assembly/machine/empty_blaze_burner")
                .baseBlock("minecraft:netherrack")
                .inputItem("minecraft:iron_bars", 4)
                .inputItem("create_expansion:wood_screw", 16)
                .outputBlock("create:empty_blaze_burner")
                .save(output);
        new AssemblyRecipeBuilder("assembly/machine/encased_fan")
                .baseBlock("create:andesite_casing")
                .inputItem("create:propeller", 1)
                .inputItem("create_expansion:wood_screw", 2)
                .inputItem("create:shaft", 1)
                .inputItem("create_expansion:wood_screw", 2)
                .outputBlock("create:encased_fan")
                .save(output);
        new AssemblyRecipeBuilder("assembly/machine/millstone")
                .baseBlock("minecraft:andesite_slab")
                .inputItem("create:cogwheel", 1)
                .inputItem("create_expansion:wood_screw", 2)
                .inputItem("create:shaft", 1)
                .inputItem("create_expansion:wood_screw", 2)
                .outputBlock("create:millstone")
                .save(output);
        new AssemblyRecipeBuilder("assembly/machine/steam_engine")
                .baseBlock("minecraft:copper_block")
                .inputItem("create:piston_extension_pole", 2)
                .inputItem("create_expansion:wood_screw", 4)
                .inputItem("create:electron_tube", 1)
                .outputBlock("create:steam_engine")
                .save(output);
        new AssemblyRecipeBuilder("assembly/machine/mechanical_crafter")
                .baseBlock("create:brass_casing")
                .inputItem("create:cogwheel", 1)
                .inputItem("create_expansion:wood_screw", 2)
                .inputItem("create:electron_tube", 1)
                .inputItem("create:crafter_slot_cover", 1)
                .outputBlock("create:mechanical_crafter")
                .save(output);
        new AssemblyRecipeBuilder("assembly/machine/spring_coiling_machine")
                .baseBlock("create:andesite_casing")
                .inputItem("create:shaft", 1)
                .inputItem("create_expansion:wrought_iron_screw", 2)
                .inputItem("create_expansion:wrought_iron_rod", 2)
                .inputItem("create_expansion:wrought_iron_screw", 4)
                .inputItem("create_expansion:wrought_iron_ring", 1)
                .inputItem("create_expansion:wrought_iron_screw", 2)
                .outputBlock("create_expansion:spring_coiling_machine")
                .save(output);
        new AssemblyRecipeBuilder("assembly/machine/kinetic_wire_drawer")
                .baseBlock("create:andesite_casing")
                .inputItem("create:shaft", 1)
                .inputItem("create_expansion:wrought_iron_plate", 1)
                .inputItem("create_expansion:wrought_iron_screw", 2)
                .inputItem("create_expansion:wrought_iron_rod", 12)
                .inputItem("create_expansion:wrought_iron_screw", 24)
                .inputItem("create_expansion:wrought_iron_plate", 1)
                .inputItem("create_expansion:wrought_iron_screw", 2)
                .inputItem("create_expansion:wrought_iron_ring", 1)
                .inputItem("create_expansion:wrought_iron_screw", 2)
                .outputBlock("create_expansion:kinetic_wire_drawer")
                .save(output);
        new AssemblyRecipeBuilder("assembly/machine/kinetic_lathe")
                .baseBlock("create:andesite_casing")
                .inputItem("create_expansion:wrought_iron_nugget", 6)
                .inputItem("create_expansion:wrought_iron_screw", 24)
                .inputItem("create_expansion:wrought_iron_screw", 2)
                .inputItem("create_expansion:wrought_iron_rod", 1)
                .inputItem("create_expansion:wrought_iron_screw", 4)
                .inputItem("create:shaft", 1)
                .inputItem("create_expansion:wrought_iron_screw", 2)
                .outputBlock("create_expansion:kinetic_lathe")
                .save(output);
        new AssemblyRecipeBuilder("assembly/machine/kinetic_rolling_mill")
                .baseBlock("create:andesite_casing")
                .inputItem("create_expansion:wrought_iron_ring", 4)
                .inputItem("create_expansion:wrought_iron_screw", 16)
                .inputItem("create:shaft", 2)
                .inputItem("create_expansion:wrought_iron_screw", 8)
                .outputBlock("create_expansion:kinetic_rolling_mill")
                .save(output);
        new AssemblyRecipeBuilder("assembly/machine/kinetic_centrifuge")
                .baseBlock("create:andesite_casing")
                .inputItem("minecraft:andesite_slab", 1)
                .inputItem("create:metal_girder", 1)
                .inputItem("create_expansion:wrought_iron_screw", 4)
                .inputItem("minecraft:spruce_log", 4)
                .inputItem("create_expansion:wrought_iron_screw", 16)
                .inputItem("create:shaft", 1)
                .inputItem("create_expansion:wrought_iron_screw", 2)
                .outputBlock("create_expansion:kinetic_centrifuge")
                .save(output);
        new AssemblyRecipeBuilder("assembly/machine/kinetic_sifter")
                .baseBlock("create:andesite_casing")
                .inputItem("create_expansion:mesh", 1)
                .inputItem("create:cogwheel", 1)
                .inputItem("create_expansion:wrought_iron_screw", 4)
                .outputBlock("create_expansion:kinetic_sifter")
                .save(output);
        new AssemblyRecipeBuilder("assembly/box/foundry_input_bus")
                .baseBlock("create_expansion:foundry_casing")
                .inputItem("create:chute", 1)
                .inputItem("create_expansion:treated_wood_screw", 2)
                .inputItem("create_expansion:treated_wood_small_gear", 1)
                .inputItem("create_expansion:treated_wood_screw", 2)
                .outputBlock("create_expansion:foundry_input_bus")
                .save(output);
        new AssemblyRecipeBuilder("assembly/box/foundry_output_hatch")
                .baseBlock("create_expansion:foundry_casing")
                .inputItem("minecraft:bucket", 1)
                .inputItem("create_expansion:treated_wood_screw", 2)
                .inputItem("create_expansion:treated_wood_gear", 1)
                .outputBlock("create_expansion:foundry_output_hatch")
                .save(output);
        new AssemblyRecipeBuilder("assembly/box/foundry_input_hatch")
                .baseBlock("create_expansion:foundry_casing")
                .inputItem("minecraft:bucket", 1)
                .inputItem("create_expansion:treated_wood_gear", 2)
                .inputItem("create_expansion:treated_wood_screw", 1)
                .outputBlock("create_expansion:foundry_input_hatch")
                .save(output);
    }
}
